name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ankit/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ankit/react-test npm test

      - name: Generate separate builds
        run: docker build -t ankit/multi-client ./client
      - name: Build server
        run: docker build -t ankit/multi-server ./server
      - name: Build worker
        run: docker build -t ankit/multi-worker ./worker
      - name: Build nginx
        run: docker build -t ankit/multi-nginx ./nginx

      - run: docker push ankit/multi-client
      - run: docker push ankit/multi-nginx
      - run: docker push ankit/multi-server
      - run: docker push ankit/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-gh
      #     environment_name: Dockergh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
